echo "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■"
echo "■           BOBUX GENERATOR             ■"
echo "■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■"
sleep 3
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...ooo"
sleep 0.05
echo "oooWait...ooO"
sleep 0.05
echo "oooWait...oOO"
sleep 0.05
echo "oooWait...OOO"
sleep 0.05
echo "ooOWait...OOO"
sleep 0.05
echo "oOOWait...OOO"
sleep 0.05
echo "OOOWait...OOO"
sleep 2
echo "loading..."
echo "■□□□□"
sleep 2
echo "■■□□□"
sleep 5
echo "■■■■■"
sleep 2
echo "Load Complete..."
echo "Bobux generator↕Ver.0.31"
 echo "Checking account..."
sleep 3
echo "[✔]Checking account..." 
sleep 1
echo "Hacking Server...."
sleep 3
echo "[✔]Hacking Server...." 
sleep 3
echo "Giving Bobux..." 
sleep 3
echo "[✔]Giving Bobux..."
sleep 1
echo "get stick bugged!!!!!!!!!!!111!!!11!!!!"
sleep 1
echo "lol, this is just joke program XD"
sleep 1
echo "lol"
